apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  releaseName: node-problem-detector
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.6.3
    name: node-problem-detector
  values:
    image:
      tag: v0.8.1
